### ISSUE TITLE
semi-automatic GPU detection and driver installation beyond Nvidia

### ISSUE THREAD

**Issue by probonopd** [broozar/installDesktopFreeBSD#1]
Thanks for making this project.

I think that this (or something like it) should become part of the official FreeBSD installer.

https://github.com/broozar/installDesktopFreeBSD/blob/a33923002deeeecf3510a924264c00fbad04cee3/files/darkmate-installer.sh#L776

Check this out:
https://github.com/nomadbsd/NomadBSD/blob/master/config/etc/rc.d/initgfx

NomadBSD was able to boot me into a working Xorg on every machine I tried so far, including Intel and Nvidia.

**Comment by broozar** [comment]
Thanks for the link. The script now offers a driver selection screen, but I decided against auto detection. I took a good look at their config files though and learned a lot.
